const dadosBiotech = {
  'medicina': [
    ['Biomonitor', '2', '300'],
    ['Plano de Saúde', '—', '—'],
    ['+ Básico', '1', '500/Mês ou 5000/Ano'],
    ['+ Ouro', '1', '2500/Mês ou 25000/Ano'],
    ['+ Platina', '1', '5000/Mês ou 50000/Ano'],
    ['+ Super-Platina', '1', '10000/Mês ou 100000/Ano'],
    ['Medkit', '3', 'Rating x250'],
    ['Suprimento (Medkit)', '1', '100'],
    ['Adesivo Antídoto', '3', '150'],
    ['Adesivo Químico', '3', '200'],
    ['Adesivo Estimulante', '3', 'Rating x25'],
    ['Adesivo Tranquilizante', '3', '(Rating x Rating) x10'],
    ['Adesivo de Trauma', '3', '500'],
  ],

  'toxinas': [
    [
      'CS/Gás Lacrimogênio',
      '8',
      '1 Turno',
      '(6-Corpo)x5 minutos; Mín: 5 minutos',
      'Contato,Inalação',
      'Dazed,Nauseated,Stun',
      '2 (L)',
      '20',
    ],
    [
      'Gamma-Scopolamina',
      '12',
      'Imediato',
      '(6-Corpo)x30 minutos; Mín: 30 minutos',
      'Injeção',
      'Dazed,Immobilized,Outro',
      '7 (I)',
      '200',
    ],
    [
      'Narcoject',
      '15',
      'Imediato',
      '(6-Corpo) Horas; Mín: 1 hora',
      'Injeção',
      'Stun',
      '4 (L)',
      '50',
    ],
    [
      'Gás Nauseante',
      '9',
      '3 Turnos',
      '(6-Corpo) Minutos; Mín: 1 minuto',
      'Inalação',
      'Dazed,Nauseated',
      '3 (L)',
      '25',
    ],
    [
      'Neuro-Stun VIII',
      '9',
      '1 Turno',
      '(6-Corpo)x10 Minutos; Mín: 10 minutos',
      'Contato,Inalação',
      'Dazed,Stun',
      '5 (L)',
      '60',
    ],
    [
      'Neuro-Stun IX',
      '12',
      '1 Turno',
      '(6-Corpo)x10 Minutos; Mín: 10 minutos',
      'Contato,Inalação',
      'Dazed,Stun',
      '6 (L)',
      '60',
    ],
    [
      'Neuro-Stun X',
      '15',
      '1 Turno',
      '(6-Corpo)x10 Minutos; Mín: 10 minutos',
      'Contato,Inalação',
      'Dazed,Stun',
      '7 (L)',
      '100',
    ],
    [
      'Pepper Punch',
      '11',
      '1 Turno',
      '(8-Corpo)x20 Minutos; Mín: 20 Minutos',
      'Contato,Inalação',
      'Blinded I,Dazed,Nauseated,Stun',
      'n/a',
      '5',
    ],
    [
      'Seven-7',
      '15',
      '1 Turno',
      '(6-Corpo)x10 Minutos; Mín: 10 minutos',
      'Contato,Inalação',
      'Blinded I,Dazed,Físico,Nauseated',
      '10 (I)',
      '1000',
    ],
  ],

  'drogas': [
    [
      'Álcool',
      '6',
      '1 Minuto',
      '(8-Corpo) Horas; Mín: 1 Hora',
      'Ingestão',
      'n/a',
      '5-500',
    ],
    [
      'Bliss',
      '8',
      '1 Turno',
      '(6-Corpo) Horas; Mín: 1 Hora',
      'Inalação,Injeção',
      '2 (I)',
      '15',
    ],
    [
      'Cram',
      '8',
      '10 Minutos',
      '(12-Corpo) Horas; Mín: 1 Hora',
      'Inalação,Ingestão',
      '2 (L)',
      '10',
    ],
    [
      'Deepweed',
      '7',
      'Imediato',
      '(6-Corpo) Horas; Mín: 1 Hora',
      'Inalação,Ingestão',
      '4 (I)',
      '400',
    ],
    [
      'Jazz',
      '9',
      'Imediato',
      '10x1D6 Minutos',
      'Inalação',
      '2 (L)',
      '75',
    ],
    [
      'Kamikaze',
      '10',
      'Imediato',
      '10x1D6 Minutos',
      'Inalação',
      '3 (L)',
      '100',
    ],
    [
      'Long Haul',
      '11',
      '10 Minutos',
      '4 Dias',
      'Injeção',
      'n/a',
      '50',
    ],
    [
      'Nitro',
      '12',
      '1 Turno',
      '10x1D6 Minutos',
      'Inalação',
      '2 (L)',
      '50',
    ],
    [
      'Novacoke',
      '12',
      '1 Turno',
      '(10-Corpo) Horas; Mín: 1 Hora',
      'Inalação,Injeção',
      '2 (L)',
      '10',
    ],
    [
      'Psyche',
      '8',
      '10 Minutos',
      '(12-Corpo) Horas; Mín: 1 Hora',
      'Ingestão',
      'n/a',
      '200',
    ],
    [
      'Zen',
      '7',
      '5 Minutos',
      '10x1D6 Minutos',
      'Inalação',
      '3 (L)',
      '5',
    ],
  ],

  'grades': [
    [
      'Normal',
      'x1',
      'x1',
      '+0',
    ],
    [
      'Usado',
      'x1,1',
      'x0,5',
      '-1',
    ],
    [
      'Alphaware',
      'x0,8',
      'x1,2',
      '+1',
    ],
    [
      'Betaware',
      'x0,7',
      'x1,5',
      '+2',
    ],
    [
      'Deltaware',
      '0,5',
      'x2,5',
      '+3'
    ],
  ],

  'cyberware': [
    [
      'Commlink',
      '0,2',
      '[2]',
      '2',
    ],
    [
      'Control Rig',
      'Rating x1',
      '-',
      '4(L)',
    ],
    [
      'Bomba de Cortex (Kink)',
      '-',
      '[1]',
      '6(I)',
    ],
    [
      'Bomba de Cortex (Micro)',
      '-',
      '[2]',
      '6(I)',
    ],
    [
      'Bomba de Cortex (Área)',
      '-',
      '[3]',
      '6(I)',
    ],
    [
      'Cyberdeck',
      '0,4',
      '[4]',
      '-',
    ],
    [
      'Datajack',
      '0,1',
      '1',
      '-',
    ],
    [
      'Datalock (1-12)',
      '0,1',
      '-',
      '-',
    ],
    [
      'Booster Olfatório (1-3)',
      '0,2',
      '-',
      '-',
    ],
    [
      'Simrig',
      '0,2',
      '-',
      '-',
    ],
    [
      'Skilljack (1-6)',
      'Rating x0,1',
      '-',
      '-',
    ],
    [
      'Booster de Paladar (1-3)',
      '0,2',
      '-',
      '-',
    ],
    [
      'Compartimento Dental',
      '-',
      '-',
      '-',
    ],
    [
      'Sensor Ultrassom',
      '0,3',
      '[2]',
      '-',
    ],
    [
      'Modulador de Voz (1-3)',
      '0,2',
      '-',
      '-',
    ]
  ]
}