const dadosEletronicos = {
    'Commlinks':[
        ['MetaLink', '1', '1/0', '0', '2', '100'],
        ['Sony Emperor', '2', '1/1', '1', '2', '700'],
        ['Renraku Sensei', '3', '2/0', '1', '2', '1000'],
        ['Erika Elite', '4', '2/1', '2', '2', '2500'],
        ['Hermes Ikon', '5', '3/0', '2', '3', '5000'],
        ['Transys Avalon', '6', '3/1', '3', '3', '8000'],
    ],
    'Cyberdecks':[
        ['Erika MCD-6', '1', '4/3', '2', '3 (I)', '24,750'],
        ['Spinrad Falcon', '2', '5/4', '4', '3 (I)', '61,500'],
        ['MCT 360', '3', '6/5', '6', '3 (I)', '95,000'],
        ['Renraku Kitsune', '4', '7/6', '8', '4 (I)', '107,000'],
        ['Shiawase Cyber-6', '5', '8/7', '10', '6 (I)', '172,500'],
        ['Fairlight Escalibur', '6', '9/8', '12', '8 (I)', '410,700'],
    ],
    'RCC':[
        ['RCC Potato', '1', '3/2', '1 (L)', '1,400'],
        ['Allegiance Control Center', '2', '3/3', '3 (L)', '8,000'],
        ['Essy Motors Dronecenter', '3', '4/4', '3 (L)', '16,000'],
        ['Horizon Overseer', '4', '5/4', '4 (L)', '32,000'],
        ['Maersk Spider', '4', '4/5', '5 (L)', '34,000'],
        ['Vulcan Liegelord', '5', '6/5', '5 (L)', '66,000'],
        ['Proteus Poseidon', '5', '5/6', '6 (L)', '68,000'],
        ['Transys Eidolon', '6', '6/5', '7 (L)', '75,000'],
        ['Ares Red Dog Series', '6', '7/6', '8 (L)', '95,000'],
        ['Aztechnology Tlaloc', '7', '8/7', '9 (L)', '140,000'],
    ],
    'Acessórios':[
        ['Luvas AR', '3', '1', '150'],
        ['Leitor Biométrico', '3', '2', '200'],
        ['Papel Eletrônico', '1', '1', '5'],
        ['Impressora', '3', '1', '25'],
        ['Link de Satélite', '4', '3', '500'],
        ['Simrig', '3', '4', '1,000'],
        ['Microfone Subvocal', '3', '2', '50'],
        ['Projetor de Trídeo', '3', '1', '200'],
        ['Trode', '3', '1', '70'],
    ],
    'Comunicação e Contramedidas':[
        ['Bug Scanner', '3', '200'],
        ['Data Tap', '2', '300'],
        ['Headjammer', '5 (I)', 'Rating x150'],
        ['Jammer (Área)', '4 (L)', 'Rating x200'],
        ['Jammer (Direcional)', '4 (L)', 'Rating x200'],
        ['Micro-Transceiver', '1', '100'],
        ['Tag Eraser', '3', '450'],
        ['Gerador de Ruído', '3', 'Rating x50'],
    ],
    'Tags':[
        ['Tags Normais', '1', '1'],
        ['Datachips', '1', '1'],
        ['Tags Stealth/Segurança', '3', '2'],
        ['Tag de Sensor', '2', '2'],
    ],
    'Software':[
        ['Autosoft', 'Rating', 'Rating x500'],
        ['Cyberprograma (Básico)', '1', '60'],
        ['Cyberprograma (Hacking)', '4 (I)', '250'],
        ['Datasoft', '2', '120'],
        ['Mapsoft', '2', '100'],
        ['Shopsoft', '2', '150'],
        ['Skillsoft', '-', '-'],
        ['+ Ativo', '4', 'Rating x5000'],
        ['+ Idioma', '2', 'Rating x1500'],
        ['+ Conhecimento', '1', '2500'],
        ['Tutorsoft', 'Rating/3 (Arredondado pra cima)', 'Rating x400'],
    ],
    'Identificação':[
        ['SIM Falso',	'4 (I)', 'Rating x2500'],
        ['Licença Falsa',	'4 (I)', 'Rating x200'],
    ],
    'Visual':[
        ['Binóculos', '1-3', '1', 'Capacidade x50'],
        ['Binóculo Óptico', '-', '1', '50'],
        ['Câmera', '1-6', '1', 'Capacidade x100'],
        ['Micro Câmera', '1', '1', '100'],
        ['Lentes de Contato', '1-3', '2', 'Capacidade x200'],
        ['Endoscópio', '-', '3', '250'],
        ['Óculos', '1-4', '1', 'Capacidade x150'],
        ['Goggles', '1-6', '1', 'Capacidade x50'],
        ['Scope', '3', '1', '300'],
        ['Monóculo', '1-4', '1', 'Capacidade x120'],
        ['Mage Goggles', '-', '5', '3000'],
        ['Periscópio', '-', '2', '50'],
    ],
    'Melhorias Visuais':[
        ['Proteção à Flare', '[1]', '1', '+250'],
        ['Image Link', '[1]', '1', '+25'],
        ['Visão Low-Light', '[1]', '2', '+500'],
        ['Smartlink', '[2]', '2', '+2000'],
        ['Visão Termográfica', '[1]', '2', '+500'],
        ['Link Ultrasound', '[1]', '1', '+300'],
        ['Melhora Visual', '[2]', '1', '+500'],
        ['Zoom', '[1]', '1', '+250'],
    ],
    'Audio':[
        ['Microfone', '1-6', '1', 'Capacidade x50'],
        ['Microfone Direcional', '1-6', '2', 'Capacidade x50'],
        ['Earbuds', '1-3', '1', 'Capacidade x50'],
        ['Fone de Ouvido', '1-6', '1', 'Capacidade x50'],
        ['Microfone à Laser', '1-6', '2', 'Capacidade x100'],
    ],
    'Melhorias Auditivas':[
        ['Melhora Auditiva', '[1]', '1', '500'],
        ['Filtro Sonoro', '[Rating]', '3', '+Rating x250'],
        ['Reconhecimento Espacial', '[2]', '2', '+1000'],
    ],
    'Sensores':[
        ['Compartimento (Mão)', '1-3', '1', 'Capacidade x100'],
        ['Compartimento (Parede)', '1-6', '1', 'Capacidade x250'],
        ['Conjunto de Sensores', 'Rating', '3', 'Rating x1000'],
        ['Único Sensor', '[1]', '2', 'Rating x100'],
    ],
    'Conjunto de Sensores':[
        ['RFID Tag, Dispositivos Audiovisuais, Headware', '2'],
        ['Drone Pequeno, Compartimento de Mão', '3'],
        ['Drone Médio, Compartimento de Parede', '4'],
        ['Drone Grande, Cyber Membro', '5'],
        ['Moto', '6'],
        ['Veículo (Maior que Moto)', '7'],
        ['Prédio, Complexo', '8'],
    ],
    'Função dos Sensores':[
        ['Sensor Atmosférico', '-'],
        ['Câmera', 'LOS'],
        ['Scanner de Cyberware', '15 metros'],
        ['Microfone Direcional', '-'],
        ['Sensor Geiger', '-'],
        ['Microfone à Laser', '100 metros'],
        ['Medidor de Distância (Laser)', '1000 metros'],
        ['Detector de Metais (MAD)', '5 metros'],
        ['Sensor de Movimento', '25 metros'],
        ['Sensor Olfatório', '-'],
        ['Microfone', '-'],
        ['Ultrassom', '50 metros'],
    ]
};
